Feat: Input component
prgrms-fe-devcourse/FEDC5_STYLED_sehee pull request #10
Opened 2023-12-28 17:32 UTC by wldlsgur

## ✨ 반영 브랜치
`feature/inputComponent` -> `dev`

## 📝 설명
재사용 가능한 input 컴포넌트를 구현했습니다.

## ✅ 변경 사항
- [x] input 컴포넌트 기능 구현
- [x] input 컴포넌트 타입 지정
- [x] input 컴포넌트 스타일 구현

## 💬 PR 포인트 & 질문사항
- 외부에서 재사용하기 좋게 구현해봤는데 혹시 부족한 부분 보이시면 코멘트 부탁드립니다!

2023-12-28 17:48 UTC, kim-hyunjoo reviewed
수고 많으셨습니다!

2023-12-28 17:48 UTC, kim-hyunjoo commented on src/Components/Base/Input/Style.ts
인혁님 Style.ts랑 Type.ts가 대문자여서.. 이거 소문자로 통합시켜줘야할 것 같습니다 ㅋㅋㅋㅋㅋ

2023-12-29 02:14 UTC, harry7435 requested changes
- ThemeProvider 사용을 하는 것을 새롭게 알아갑니다!

- 스타일 컴포넌트 부분에 네이밍과 제네릭 타입 분리 쪽 조금 수정이 필요할 거 같아요!

2023-12-29 02:14 UTC, harry7435 commented on src/Components/Base/Input/Style.ts
> +  display: ${({ $block }) => ($block ? 'block' : 'inline-block')};
P4: 스타일 컴포넌트 네이밍 StyledWrapper로 하기로 했었던 거 같네요!
<{ $block?: boolean }> 제네릭에 들어가는 타입 같은 경우도 추후 유지보수를 위해 type.ts에 따로 타입을 선언해서 가져오는게 좋을거 같아요!

아래 Label 스타일 컴포넌트도 체크해주시면 감사하겠습니다!

2023-12-29 02:14 UTC, harry7435 commented on src/Components/Base/Input/index.tsx
> +  }, [initialFocus]);
초기 포커스 설정 잘해주셨네요 👍

2023-12-29 02:51 UTC, w00ngja commented on src/Components/Base/Input/Style.ts
> +  font-size: ${({ theme }) => theme.size.medium};
오 이것도 props. 생략가능하네요!!

2023-12-29 02:56 UTC, wldlsgur commented on src/Components/Base/Input/Style.ts
> +  display: ${({ $block }) => ($block ? 'block' : 'inline-block')};
제네릭보다 Props 역할인 것 같습니다! Props라도 따로 타입을 지정하는게 좋을까요?

2023-12-29 04:47 UTC, harry7435 commented on src/Components/Base/Input/Style.ts
> +  display: ${({ $block }) => ($block ? 'block' : 'inline-block')};
props도 타입이 길어진다면 분리하면 좋을 거 같은데 현재 컴포넌트는 굳이 분리해야 하나 싶기도 하네요..

2023-12-29 04:48 UTC, harry7435 approved these changes

2023-12-29 04:49 UTC, w00ngja approved these changes

2023-12-29 04:50 UTC, kim-hyunjoo approved these changes

2023-12-29 04:51 UTC, merged