Feat: Header 컴포넌트
prgrms-fe-devcourse/FEDC5_STYLED_sehee pull request #32
Opened 2024-01-02 17:38 UTC by miloul

## ✨ 반영 브랜치
`feature/HeaderComponent` -> `dev`

## 📝 설명
Header 컴포넌트

## ✅ 변경 사항
- [x] 알람 모달, 검색 모달, 글 작성 모달, 다이렉트 메시지 페이지 파일 임의 생성 및 연결
- [x] Header `position: sticky`로 상단 고정 
- [x] RouteManager 내부의 <BrowserRouter> App.tsx로 빼기 
- [x] Header 내에 HeaderTab, HeaderUser 로 분리
- [x] 추후 수정이 필요한 부분 주석으로 명시 

## 💬 PR 포인트 & 질문사항
.

## 📢 이슈 정보
.

2024-01-03 06:27 UTC, harry7435 commented on src/Components/Common/Header/style.ts
> +  height: 9.4rem;
P5: 이 높이를 정하신 기준은 어떤걸까요? 저도 mainPage 컴포넌트 만들기 위해서는 Header 컴포넌트 높이를 뺀 것만큼 구현을 해야해서요!

2024-01-03 06:30 UTC, miloul commented on src/Components/Common/Header/style.ts
> +  height: 9.4rem;
피그마 상에서 94px로 되어있어 9.4rem으로 했습니다!

2024-01-03 07:38 UTC, kim-hyunjoo reviewed
Header에 은근히 넣어야 할 컴포넌트가 많네요... 고생 많으셨습니다!!

2024-01-03 07:38 UTC, kim-hyunjoo commented on src/Components/Common/Header/HeaderTab/index.tsx
> +          key={Number(index)}
아마 여기서는 문제 없을텐데, React 공식 문서에서 index를 key로 사용하는 것을 권장하지 않는다구 합니당!! 만약 다음에 map을 사용한다면 고유한 값을 넣어주면 좋을 것 같아요! 보통 id값을 넣는데 여기는 id가 없으므로 name을 넣어줘도 될 것 같군요... ㅎㅎ
[[React] 배열의 index를 key로 쓰면 안되는 이유](https://medium.com/sjk5766/react-%EB%B0%B0%EC%97%B4%EC%9D%98-index%EB%A5%BC-key%EB%A1%9C-%EC%93%B0%EB%A9%B4-%EC%95%88%EB%90%98%EB%8A%94-%EC%9D%B4%EC%9C%A0-3ce48b3a18fb)

2024-01-03 07:38 UTC, kim-hyunjoo commented on src/Components/Common/Header/HeaderTab/index.tsx
> +          }
스타일 관련 속성은 styled Component 내에서 props로 처리하시는 게 좋을 것 같아요!

2024-01-03 07:38 UTC, kim-hyunjoo commented on src/Components/Common/Header/index.tsx
> +      </Link>
이 부분도 HeaderLogo 이런식으로 디렉토리 분리하면 좋을 것 같습니다!

2024-01-03 07:38 UTC, kim-hyunjoo commented on src/Components/Common/Header/HeaderTab/style.ts
> +  t cborder-left: 1px solid gray;
여기 오타난 것 같아요...!!

2024-01-03 07:38 UTC, kim-hyunjoo commented on src/Components/Common/Header/HeaderTab/index.tsx
> +import { StyledNavContainer } from '../style';
`import StyledNavContainer from './style';` 로 수정하고, Header/style.ts에서는 StyledNavContainer 지워도 될 것 같아요. 지금 중복되는 코드가 몇 개 있는 것 같아서... 다시 한 번 쭉 확인 해보시고 중복되는 건 삭제한다던가... 조금 정리를 해야할 것 같습니당

2024-01-03 07:38 UTC, kim-hyunjoo commented on src/Components/Common/Header/HeaderUser/index.tsx
> +    { name: 'send' },
send 보다는 directMessage가 더 좋을 것 같네유 ㅎㅎ

2024-01-03 07:38 UTC, kim-hyunjoo commented on src/Components/Common/Header/HeaderUser/index.tsx
> +    { name: 'account_circle' },
저희 그리고 camelCase 사용하기로 해서, 이런 이름들도 다 camelCase로 바꿔주면 좋을 것 같습니다!

2024-01-03 07:50 UTC, kim-hyunjoo commented on src/Components/Common/Header/HeaderUser/index.tsx
> +  const [isUser, setUser] = useState(false);
isAuthUser 이 조금 더 명확한 명칭이 될 것 같습니다!! 저희가 인증/미인증 사용자로 나누기로 해가지궁ㅋㅋㅋㅋ

2024-01-03 07:53 UTC, kim-hyunjoo commented on src/Components/Common/Header/HeaderUser/index.tsx
> +  const [isUser, setUser] = useState(false);
아 그리고 setIsUser로 바꿔야해요! 만약 isAuthUser로 바꿀거면 setIsAuthUser

2024-01-03 08:43 UTC, miloul commented on src/Components/Common/Header/HeaderUser/index.tsx
> +    { name: 'send' },
앗 요거 이름은 아이콘에서 가져오는 이름입니다! ㅎㅎ

2024-01-03 08:49 UTC, miloul commented on src/Components/Common/Header/index.tsx
> +      </Link>
넵~! 수정하겠습니당

2024-01-03 08:50 UTC, kim-hyunjoo commented on src/Components/Common/Header/HeaderUser/index.tsx
> +    { name: 'send' },
헐 제가 알못이네요 죄송합니다 😭😭😭

2024-01-03 08:54 UTC, miloul commented on src/Components/Common/Header/HeaderTab/index.tsx
> +import { StyledNavContainer } from '../style';
맨첨에 Header에 다 넣어놓고 중복되는 거 분리한 거라 남아있는 게 있었네요 ㅜㅜ 한번 살펴보면서 중복 코드 정리하겠습니다!

2024-01-03 08:55 UTC, miloul commented on src/Components/Common/Header/HeaderTab/index.tsx
> +          key={Number(index)}
아하 몰랐네요! 넵 수정하겠습니다! 배워갑니다 ㅎㅎ 👍👍

2024-01-03 09:58 UTC, miloul commented on src/Components/Common/Header/HeaderTab/index.tsx
> +          }
넵~! 반영해서 수정했습니다!

2024-01-03 10:21 UTC, w00ngja approved these changes
고생 많으셨습니다 승민님! Header 컴포넌트도 규모가 장난 아니네요.. 로직 이해에도 큰 어려움이 없었고 더미데이터도 잘 들어 있어 쉽게 테스트해볼 수 있었던 것 같습니다! 추후에 헤더 높이나 아이콘 크기들을 조금씩 줄여도 괜찮을 것 같다는 생각..?을 개인적으로 해보았습니다..😊

2024-01-03 10:21 UTC, w00ngja commented on src/Components/Common/Header/HeaderTab/index.tsx
> +          }
공용 컴포넌트라 승민님께서 Inline prop으로 넘겨주신 것 같은데요..! Button 컴포넌트를 베이스로한 스타일 컴포넌트를 추가적으로 만들어 사용하는 편이 좋을까요? 🤔

2024-01-03 10:21 UTC, w00ngja commented on src/Components/Common/Header/HeaderUser/index.tsx
> +  const userArr = [
상수화가 잘 되어 있어 좋은 것 같습니다! 👍🏻

2024-01-03 10:21 UTC, w00ngja commented on src/Components/Common/Header/HeaderTab/style.ts
> +const StyledNavContainer = styled(StyledLogoContainer)`
사용에는 지장이 없지만 동일한 계층의 StyledLogoContainer로부터 확장하기 보단 `StyledContainer`등으로 추상화해 `LogoContainer`와 `NavContainer`에 내려주는 건 어떨까 하고 생각해 보았습니당..😳

2024-01-03 10:21 UTC, w00ngja commented on src/Components/Common/Header/HeaderUser/index.tsx
> +          <Button
승민님은 공용 컴포넌트 사용하시면서 불편한 점 없으셨나요? 사용하시다가 언제라도 발생하면 말씀해주세요~~

2024-01-03 13:04 UTC, wldlsgur reviewed
승민님 헤더 많이 고생하셨습니다 ㅜㅜ

헤더 내부에 아이템 분리 기준으로 bold 처리 되어있는데 피그마에서는 section으로 분리해서 bold처럼 보일꺼에요!! 그래서 실제로는 bold 처리 안하셔도 좋을 것 같습니다!

2024-01-03 13:33 UTC, miloul commented on src/main.tsx
> +  </BrowserRouter>,
react-router-dom을 적용하고 싶을 때 최상위에 있어야하는 컴포넌트로 알고있습니당!

[리액트 라우터(React Router) - BrowserRouter, HashRouter, Route, Switch, Link (Feat. SPA)](https://velog.io/@wiostz98kr/TIL49-l-React-%EB%A6%AC%EC%95%A1%ED%8A%B8-%EB%9D%BC%EC%9A%B0%ED%84%B0React-Router-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0-Feat.-SPA#31-browserrouter)

2024-01-03 13:38 UTC, miloul commented on src/Components/Common/Header/HeaderTab/style.ts
> +const StyledNavContainer = styled(StyledLogoContainer)`
오 좋네요! 수정하겠습니당!

2024-01-03 14:01 UTC, miloul commented on src/Components/Common/Header/HeaderTab/index.tsx
> +          }
공용 컴포넌트라 inline prop으로 넘겨준 거긴 한데 지금 생각해보니 그런 것 같네요..
제가 수정해두긴 했는데 갑자기 궁금해서요!
혹시 현주님은 왜 styled component 내에서 처리하는 걸 추천하신 건지 물어봐도 될까요?

2024-01-03 17:56 UTC, harry7435 commented on src/Components/Common/Header/HeaderLogo/index.tsx
> +          src={colors.background === '#000000' ? logoWhite : logoBlack}
P5: 나중에 ligththeme 인지에 대한 상태 값에 따라 변경하도록 리팩토링하면 될 거 같습니다!

2024-01-03 17:56 UTC, harry7435 commented on src/Components/Common/Header/style.ts
> +`;
P5: StyledContainer 가 가로 너비가 줄어들면 이렇게 작아지더라구요!
고정 높이나 너비를 지정해주는 것이 좋을 거 같아요!
![image](https://github.com/prgrms-fe-devcourse/FEDC5_STYLED_sehee/assets/70748442/9702a848-16ca-49f5-85a1-dddf63e3c798)

2024-01-03 17:56 UTC, harry7435 commented on src/Components/Common/Header/HeaderLogo/style.ts
> +  width: 9rem;
따로 너비를 지정하신 이유가 있을까요?

2024-01-03 17:56 UTC, harry7435 commented on src/Components/Common/Header/HeaderTab/index.tsx
> +                    setTab(0);
P4: directmessage 페이지에서 검색 모달을 켰다가 모달을 닫으면 라우팅은 /directmessage인데 탭이 홈 탭으로 돌아가더라구요!
react-router의 `useLocation`을 통해 현재 url이 `/directmessage`일 경우에는 바로 return에서 `setTab(0)`이 되는 것을 막으면 어떨까요?

2024-01-03 17:56 UTC, harry7435 commented on src/Components/Common/Header/HeaderTab/index.tsx
> +                    setTab(0);
확인해보니 PostModal에서도 같은 이슈가 발생하네요! 수정하신다면 두 `onChangeOpen` props 내에서 동일하게 수정해줘야 할 거 같습니다!

2024-01-03 17:56 UTC, harry7435 commented on src/Components/Common/Modal/SearchModal/index.tsx
> +    </Modal>
P4: 모달마다 배경색이 똑같이 rgba(0,0,0,0.5)로 지정을 했었는데 색깔이 다르네요,,, 설정은 똑같은데 왜 색깔이 다른지 모르겠네요 ㅠㅠ
![image](https://github.com/prgrms-fe-devcourse/FEDC5_STYLED_sehee/assets/70748442/00092778-0c77-4991-8796-bf8de6ea79c2)
![image](https://github.com/prgrms-fe-devcourse/FEDC5_STYLED_sehee/assets/70748442/d858d31c-58fc-4da7-b27e-5e1350a9734b)

2024-01-03 17:56 UTC, harry7435 commented on src/Components/Common/Header/HeaderTab/index.tsx
> +          {items.name === 'add_circle'
P3: 모달 색이 다른 이유를 찾았습니다... 검색 탭을 누르면 홈탭에도 중복해서 모달이 열리네요...
뭔가 조건 설정에서 오류가 있는 듯 합니다!
HeaderUser에서도 동일한 로직을 사용하셔서 HeaderUser에서 프로필 버튼을 누르면 똑같이 모달이 중복해서 생성됩니다.
![image](https://github.com/prgrms-fe-devcourse/FEDC5_STYLED_sehee/assets/70748442/e8e4b229-4e80-4d31-9ba4-04c4a53709c9)

2024-01-03 17:59 UTC, harry7435 requested changes
헤더 컴포넌트를 깔끔하게 구현하셨네요!! 라우팅에서 내부 상태 관리까지 👍👍
모달 중복 생성 관련 이슈와 자잘한 css 부분만 수정하면 될 거 같습니다!

2024-01-03 17:59 UTC, harry7435 commented on src/Components/Common/Modal/SearchModal/index.tsx
> +    </Modal>
https://github.com/prgrms-fe-devcourse/FEDC5_STYLED_sehee/pull/32/files#r1440739536
이슈 원인입니다.

2024-01-03 17:59 UTC, harry7435 commented on src/Components/Common/Header/HeaderUser/index.tsx
> +                dropdown && <Modal onChangeOpen={() => setDropdown(false)} />}
https://github.com/prgrms-fe-devcourse/FEDC5_STYLED_sehee/pull/32/files#r1440739536
P3: 같은 이슈가 발생합니다!

2024-01-05 01:35 UTC, wldlsgur approved these changes

2024-01-07 22:24 UTC, miloul commented on src/Components/Common/Header/HeaderLogo/style.ts
> +  width: 9rem;
너비를 지정하지 않으면 로고 사진이 너무 커 헤더 바깥으로 나오게 되어서 따로 너비 지정했습니다!

2024-01-10 01:57 UTC, harry7435 approved these changes
변경사항 확인했습니다!!

2024-01-10 05:16 UTC, wldlsgur commented
승민님 헤더 작업하신다고 고생 많으시네요 ㅜㅜ 실행해봤는데 몇 가지 오류 있어서 남겨드립니다!

1. 메세지 페이지 들어갔다가 뒤로 가기 후 홈 아이콘에 밑 줄이 그여지지 않고 여전히 메세지 페이지에 밑 줄이 그여집니다! 이 상태에서 다른 아이콘 눌렀다가 홈으로 돌아와도 메세지 페이지에 밑줄이 여전히 남아있는 문제가 있습니다!

2. 로고 아이콘 호버 시 pointer가 되는 범위가 좀 큰?? 느낌이 없지 않아 있는 것 같습니다! 로고를 감싸는 div 태그를 img에 맞게 설정해주시면 해결될 것 같습니다!

3. 사용자 프로필 아이콘 클릭 시 드롭 다운보다 드롭 리스트를 바로 보여줘도 좋을 것 같은데 어떻게 생각하시나요!

2024-01-10 06:17 UTC, miloul commented
> 1. 메세지 페이지 들어갔다가 뒤로 가기 후 홈 아이콘에 밑 줄이 그여지지 않고 여전히 메세지 페이지에 밑 줄이 그여집니다! 이 상태에서 다른 아이콘 눌렀다가 홈으로 돌아와도 메세지 페이지에 밑줄이 여전히 남아있는 문제가 있습니다!
* 해당사항 zustand로 tab 관리해서 해결했습니다! 그런데 브라우저 뒤로가기 버튼 클릭시에는 어떤 식으로 처리해야할지 모르겠네요  😭 `popstate` 이벤트 붙여도 안되는 거 같아서.. ㅜㅜ
> 2. 로고 아이콘 호버 시 pointer가 되는 범위가 좀 큰?? 느낌이 없지 않아 있는 것 같습니다! 로고를 감싸는 div 태그를 img에 맞게 설정해주시면 해결될 것 같습니다!
* div 태그 말고 img 태그에 링크 달아줘서 반영했습니다~!

2024-01-10 13:17 UTC, w00ngja approved these changes
고생 많으셨습니다 승민님!

2024-01-11 00:42 UTC, miloul commented on src/Components/Common/Header/HeaderTab/index.tsx
> +            color={colors.primary}
오 좋네요 반영하겠습니다~!

2024-01-11 00:42 UTC, miloul commented on src/Components/Common/Header/index.tsx
> +  const { prev, setTab } = useTabStore();
브라우저 뒤로가기 눌렀을 때 tab이 변경 안되어서 추가한 건데 잘 안되어가지고 ㅜㅜ 지금은 주석처리해둔 상태입니다!

2024-01-11 01:14 UTC, merged