Feat: Button 컴포넌트 추가
prgrms-fe-devcourse/FEDC5_STYLED_sehee pull request #8
Opened 2023-12-28 16:04 UTC by w00ngja

## ✨ 반영 브랜치
`feature/buttonComponent` -> `dev`

## 📝 설명
1. `버튼` 공용 컴포넌트입니다. 색상과 크기, 테두리 둥근 정도를 필수로 전달받고 토글버튼 여부와 콜백함수들을 선택적으로 전달받습니다.
2. 색상(color)과 테두리 둥근 정도(borderRound)는 문자열 형태로 입력받아 프리셋을 통해 부여되도록 구현하였습니다.

## ✅ 변경 사항
- [x] 파라미터 설정 및 `ButtonProp` 타입 부여
- [x] Props 바인딩
- [x] 스타일 프리셋 설정
- [x] 토글 버튼인 경우의 로직 구현

## 💬 PR 포인트 & 질문사항
- 입력 파라미터 관련 개선사항이 있을까요?
- `width`, `height`를 필수 프롭으로 전달받아야 할까요?
- `width`, `height`, `border-radius`에도 반응형 단위가 부여되도록 구현하는게 맞을까요? (테두리가 "`extra-small`rem" 일 때도 너무 둥글어요..ㅜ)
- 토글 버튼일 경우 `isActive` 상태를 통해 토글 여부를 관리하고, `onActiveChange` 콜백을 통해 현재 토글 상태를 상위 컴포넌트에게 전달하는 방식으로 구현해보았는데 보시고 피드백 부탁드립니다.
- 전역 `defaultTheme`의 색상이 다소 한정적이라 `Hover` 효과 구현을 보류하였습니다. 사용되는 색상들이 밝기? 상황?별로 구현된 색상표를 객체 형태로 관리하면 좋을 것 같아요~~

2023-12-28 17:09 UTC, kim-hyunjoo reviewed
수고 많으셨습니다!

2023-12-28 17:09 UTC, kim-hyunjoo commented on src/Components/Base/Button/index.tsx
> +  };
개인적인 의견으로... onActiveChange랑 onClick 각각 받아와서 분리할 필요가 있을까 싶긴 하네요...?

어차피 함수의 내용은 저희가 버튼 컴포넌트 사용하면서 매개변수로 넘겨주며 정의 할거고, 여기서 이름만 이 함수로 사용하는거니까 그냥 `onClick 으로 매개변수(함수)를 통합` 시켜도 좋을 것 같아요. 만약 토글 버튼으로 사용하게 되면 어차피 onClick() 매개변수(함수)는 비어있을 거고, 그냥 일반 버튼으로 사용하게 된다면 onActiveChange가 비어있을 거라서...

```suggestion
  const handleToggle = () => {
      setIsActive(!isActive);
      onClick(isActive);
  }
  const handleClick = () => {
    onClick();
  };
```

```jsx
<StyledButton
      onClick={ isToggle ? handleToggle : handleClick }
      ....
>
```

이렇게 분리해보는 건 어떨까요? 하나의 함수에서 flag를 사용해 분기하는 것보다는, 하나의 함수에서는 하나의 기능만 하는게 좋을 것 같아서요 ㅎㅎ
혹시 제가 잘못 이해한게 있다면 말씀해주십쇼....

2023-12-28 17:09 UTC, kim-hyunjoo commented on src/Components/Base/Button/style.ts
> +  $isActive: boolean;
여기 있는 것도 types.ts에 분리해서 정의한 다음 한 줄로 줄여도 좋을 것 같아요! ㅎㅎ

2023-12-28 17:18 UTC, harry7435 commented on src/Components/Base/Button/index.tsx
> +    if (isToggle) {
`isToggle` props가 false로 주어지면 토글이 작동하지 않는 건가요?

2023-12-28 17:18 UTC, harry7435 commented on src/Components/Base/Button/index.tsx
> +  onActiveChange = () => {},
P5: onClick, onActiveChange 함수의 기본값을 지정해주신 이유가 있나요?

2023-12-28 17:18 UTC, harry7435 commented on src/Components/Base/Button/style.ts
> +
프리셋 설정은 처음 보네요! 저도 조건에 따른 css 분기 처리를 다음부터 이렇게 진행해야 겠어요! 👍

2023-12-28 17:18 UTC, harry7435 commented on src/Components/Base/Button/style.ts
> +  `,
P5: 이렇게 조건에 따라 css 분기하는것을 switch 구문을 통해 구현하는 것과는 차이가 있을까요?

2023-12-28 17:18 UTC, harry7435 commented on src/Components/Base/Button/style.ts
> +  $color: 'default' | 'black' | 'gray' | 'white' | 'blue' | 'purple';
P5: color에 대한 선택지를 이렇게 설정하신 이유가 있나요?

2023-12-28 17:18 UTC, harry7435 commented on src/Components/Base/Button/type.ts
> +export interface ButtonProp extends ButtonHTMLAttributes<HTMLButtonElement> {
P5: `extends ButtonHTMLAttributes<HTMLButtonElement>` 부분을 styled component div 태그에서도 적용이 가능한가요?

2023-12-28 17:25 UTC, harry7435 reviewed
- 입력 파라미터 관련 개선사항이 있을까요?
> 파라미터에 onClick과 onActiveChange 기본값 관련해서 체크해보아야 할 거 같습니다.
https://github.com/prgrms-fe-devcourse/FEDC5_STYLED_sehee/pull/8/files#r1437787631

- width, height를 필수 프롭으로 전달받아야 할까요?
> 선택 속성으로 하고 설정값이 없다면 기본값 제공하는 것이 좋을 듯 합니다.

- width, height, border-radius에도 반응형 단위가 부여되도록 구현하는게 맞을까요? (테두리가 "extra-smallrem" 일 때도 너무 둥글어요..ㅜ)
> 전 border-radius는 px로 해도 된다고 생각합니다. width와 height는 rem 단위로 해도 좋을 거 같아요

- 토글 버튼일 경우 isActive 상태를 통해 토글 여부를 관리하고, onActiveChange 콜백을 통해 현재 토글 상태를 상위 컴포넌트에게 전달하는 방식으로 구현해보았는데 보시고 피드백 부탁드립니다.
> 토글 작동에 약간 문제가 있는거 같습니다.
https://github.com/prgrms-fe-devcourse/FEDC5_STYLED_sehee/pull/8/files#r1437787339

- 전역 defaultTheme의 색상이 다소 한정적이라 Hover 효과 구현을 보류하였습니다. 사용되는 색상들이 밝기? 상황?별로 구현된 색상표를 객체 형태로 관리하면 좋을 것 같아요~~
> 색상 팔레트 파일을 하나 만드는 것도 좋다고 생각합니다.

2023-12-29 01:05 UTC, w00ngja commented on src/Components/Base/Button/index.tsx
> +  };
onClick으로 IsActive를 전달할 생각을 못하고 있었네요..🥲 제안 주신 것처럼 onClick에서 IsToggle을 기준으로 로직을 다르게 처리하는 게 불필요한 콜백 사용을 줄일 수 있어 좋은 것 같습니다 👍🏻👍🏻

2023-12-29 01:09 UTC, w00ngja commented on src/Components/Base/Button/index.tsx
> +    if (isToggle) {
네 false인 경우 인자로 받은 콜백만 전달하도록 구현한 것인데, 피드백 주시면 감사드리겠습니다 (__)

2023-12-29 01:12 UTC, w00ngja commented on src/Components/Base/Button/index.tsx
> +  onActiveChange = () => {},
interface 지정할 때 두 콜백을 선택 프롭으로 지정해주었더니 기본값을 부여하지 않으면 에러가 발생하더라고요..? 그래서 일단 부여해놓은 상태인데, 혹시 다른 해결법을 알고 계신다면 공유해주시면 감사드리곘습니다!

(+ 아마 리팩토링 간 onActiveChange를 제거하고 onClick을 필수 프롭으로 바꾸게 될 것 같습니다.)

2023-12-29 01:16 UTC, w00ngja commented on src/Components/Base/Button/style.ts
> +  `,
두 방법 다 사용이 가능하지만, `렌더링 성능`과 `호출할 때의 가독성 측면`에서 객체 형태로 관리하는 것이 더 용이하다고 하네요!

2023-12-29 01:22 UTC, w00ngja commented on src/Components/Base/Button/style.ts
> +  $color: 'default' | 'black' | 'gray' | 'white' | 'blue' | 'purple';
피그마를 통해 추상화할 수 있는 부분을 찾아보았는데, 개인적으로 `색상 테마`(배경색, 내용색, Hover 시 효과 등)를 기준으로 컴포넌트를 만들어 사용하면 일관성을 유지할 수 있을 것 같아 위와 같이 설정하였습니다. 피드백 부탁드립니다!

2023-12-29 01:24 UTC, w00ngja commented on src/Components/Base/Button/type.ts
> +export interface ButtonProp extends ButtonHTMLAttributes<HTMLButtonElement> {
개인적으로 div에는 적용해본 적이 없어 정확히 모르겠지만, 스크럼 간 인혁님이 말씀하신 처럼 HTMLAttributes로 적용이 가능한 것으로 보입니다!

2023-12-29 01:25 UTC, harry7435 commented on src/Components/Base/Button/index.tsx
> +    if (isToggle) {
아 의도하신 구현이었군요! 그럼 상관없을 꺼 같습니다!
대신 isToggle은 토글이 되었다 안 되었다를 의미하는 네이밍이니 props 명을 수정해야 할 꺼 같습니다.

2023-12-29 01:43 UTC, harry7435 commented on src/Components/Base/Button/index.tsx
> +  onActiveChange = () => {},
```
  const handleClick = () => {
    if (isToggle && onActiveChange) {
      setIsActive(!isActive);
      onActiveChange(isActive);

      return;
    }

    if (onClick) onClick();
  };
```
기본값 제거하고 `handleClick` 함수를 위와 같이 함수에 대한 가드를 설정해주니 해결되는 거 같아요!

2023-12-29 01:44 UTC, harry7435 commented on src/Components/Base/Button/style.ts
> +  `,
그런 차이가 있었군요!! 저도 앞으로 이렇게 분기해야겠어요

2023-12-29 01:45 UTC, harry7435 commented on src/Components/Base/Button/style.ts
> +  $color: 'default' | 'black' | 'gray' | 'white' | 'blue' | 'purple';
피그마 디자인 시안을 기준으로 세세한 hex color 값 나중에 바꿔주면 되겠네요!

2023-12-29 01:46 UTC, harry7435 requested changes
함수 가드 수정 코드 코멘트해뒀습니다!

2023-12-29 01:47 UTC, wldlsgur reviewed
- width, height, border-radius에도 반응형 단위가 부여되도록 구현하는게 맞을까요? (테두리-가 "extra-smallrem" 일 때도 너무 둥글어요..ㅜ)

theme에 원하는 설정 값이 없다면 바로 작성하셔도 됩니다! 만약 자주 사용되는 값이면 theme에 추가하셔서 작업하셔도 괜찮아요!!

- 전역 defaultTheme의 색상이 다소 한정적이라 Hover 효과 구현을 보류하였습니다. 사용되는 색상들이 밝기? 상황?별로 구현된 색상표를 객체 형태로 관리하면 좋을 것 같아요~~

일단 저도 피그마 기준으로 색상을 다 넣긴 했는데 누락된 부분이 있으시면 같이 추가해보는 것도 좋아요~!

2023-12-29 01:47 UTC, wldlsgur commented on src/Components/Base/Button/index.tsx
> +  height,
네네 저도 width, height 선택으로 받고 디폴트 값도 설정해주면 좋을 것 같아요.

추가하자면 color, borderRound, +backgroundColor도 저희 서비스에 자주 사용되는 형식으로 디폴트 값으로 설정해주시면 사용할 때 엄청 편리할 수 있을 것 같아요!

2023-12-29 01:47 UTC, wldlsgur commented on src/Components/Base/Button/style.ts
> +  `,
오 이렇게 객체화 시키는 방법도 있군요 처음 알았습니다!

다만 만약 default를 제외하면 색상이 선택된 경우 다크모드로 변경될 때 아무런 반응이 없지 않을까 생각됩니다!

2023-12-29 01:47 UTC, wldlsgur commented on src/Components/Base/Button/style.ts
> +  $isActive: boolean;
color, borderRound 타입도 확장성을 생각하면 일단 string으로 열어두는게 더 편할 것 같아요!

2023-12-29 01:47 UTC, wldlsgur commented on src/Components/Base/Button/index.tsx
> +  };
isToggle의 역할이 토글 버튼일 때 기능이군요!

저도 먼가 재웅님처럼 구현했을 것 같은데 현주님이 수정해주신거 보니깐 가독성이 엄청 좋네요... 저는 좋은 방법인 것 같습니다.

그리고 콜백함수를 선택적으로 받으셔서 onClick && onClikc(), onActiveChange && onActiveChange(isActive);으로 최적화도 가능할 것 같습니다!

2023-12-29 01:48 UTC, harry7435 approved these changes

2023-12-29 01:51 UTC, harry7435 approved these changes

2023-12-29 02:25 UTC, w00ngja commented on src/Components/Base/Button/style.ts
> +  `,
맞아요 해당 부분은 추후 수정이 필요할 것 같습니다.. 색상표 등과 함께 후순위 Task로 넣어놓아도 좋을 것 같습니다!

2023-12-29 02:28 UTC, w00ngja commented on src/Components/Base/Button/index.tsx
> +  };
넵 논리연산자 사용 시 ESLint 에러를 발생시켜, 익준님께서 달아주신 코멘트 형식(https://github.com/prgrms-fe-devcourse/FEDC5_STYLED_sehee/pull/8#discussion_r1437943802) 처럼 최적화 반영할 예정입니다!

2023-12-30 06:53 UTC, wldlsgur approved these changes

2023-12-31 12:57 UTC, miloul approved these changes

2023-12-31 13:49 UTC, merged