Feat: Common Modal 컴포넌트 구현
prgrms-fe-devcourse/FEDC5_STYLED_sehee pull request #9
Opened 2023-12-28 16:40 UTC by harry7435

## ✨ 반영 브랜치
`feature/modalComponent` -> `dev`

## 📝 설명
Common 재사용 가능한 Modal 컴포넌트를 구현했습니다.

## ✅ 변경 사항
- [x] `src/Components/Common/Modal` 폴더 내에 컴포넌트 구현
- [x] `type.ts`로 props 타입 분리
- [x]  width, height, border-radius, flex-direction과 같은 모달 전체 스타일 props로 설정 가능
- [x] `isOpen` props로 모달 열고 닫기 가능
- [x] 외부 `setIsOpen` 함수와 `onChangeOpen` 함수 연결 

## 💬 PR 포인트 & 질문사항
- 타입과 스타일 컴포넌트 분리가 제대로 이루어진 건지 봐주세요!
- 원래는 외부 버튼에 대한 ref를 가져와서 이벤트를 설정하려고 했으나 ref가 계속 `null`값으로 받아와져서 포기했어요...
- 대신 모달 선언하는 컴포넌트에서 `isOpen` 상태와 모달을 여는 버튼 컴포넌트를 추가하여 연결만 하면 가능하도록 구현했습니다.

2023-12-28 17:34 UTC, kim-hyunjoo reviewed
수고 많으셨습니다!

2023-12-28 17:34 UTC, kim-hyunjoo commented on src/Components/Common/Modal/index.tsx
> +const StyledModalWrapper = styled.div<StyledModalWrapperType>`
Style 컴포넌트가 3개나 있네욬ㅋㅋㅋ 얘네들은 styles.ts에 분리하는게 좋을 것 같습니당 ㅎㅎ

2023-12-28 17:34 UTC, kim-hyunjoo commented on src/Components/Common/Modal/index.tsx
> +  const handleModalBgClick = (e: MouseEvent) => {
음.. 저희 약어 사용은 지양하기로 했으니까... 그렇다고 풀어서 쓰기엔 너무 길어질 것 같고...
차라리 handleModalClose 이런건 어떤가요 ㅋㅋㅋㅋ 그냥 의견입니닷...

2023-12-28 17:34 UTC, kim-hyunjoo commented on src/Components/Common/Modal/index.tsx
> +  const handleModalBgClick = (e: MouseEvent) => {
근데 이거 혹시 그냥 ref 값 안넘겨주고, onclick했을 때 if문 없이 바로 onChangeOpen(false)를 하면 문제가 생기나요?

2023-12-28 17:34 UTC, kim-hyunjoo commented on src/Components/Common/Modal/index.tsx
> +  flexDirection = 'row',
이 속성 넣어준거 너무 굿굿

2023-12-28 17:34 UTC, kim-hyunjoo commented on src/Components/Common/Modal/index.tsx
> +  onChangeOpen,
보통 이거 useState 값 세트로 넣지 않나요? [isOpen, setIsOpen] 이렇게... 이 onChangeOpen도 setIsOpen이라고 이름 지어주는 게 어떨까요? ㅎㅎ

2023-12-29 01:01 UTC, harry7435 commented on src/Components/Common/Modal/index.tsx
> +  onChangeOpen,
어.. isOpen과 setIsOpen도 외부에 있는거라 내부에서는 boolean 값만 전달하는 함수로 생각해서 이렇게 명명했었습니다! 이름이 같으면 헷갈릴까봐서요

2023-12-29 01:02 UTC, harry7435 commented on src/Components/Common/Modal/index.tsx
> +const StyledModalWrapper = styled.div<StyledModalWrapperType>`
안 그래도 빼야 하는거 까먹고 있었어요! 분리하겠습니다!

2023-12-29 01:03 UTC, harry7435 commented on src/Components/Common/Modal/index.tsx
> +  const handleModalBgClick = (e: MouseEvent) => {
혹시나 있을 이벤트 버블링을 방지하고자 배경에 대한 currentTarget이 일치할 때만 이벤트가 동작하도록 조건을 추가했습니다!

2023-12-29 01:04 UTC, harry7435 commented on src/Components/Common/Modal/index.tsx
> +  const handleModalBgClick = (e: MouseEvent) => {
핸들러 함수명은 handleModalClose 이게 오히려 직관적이겠네요! 바꿀께요!

2023-12-29 02:06 UTC, w00ngja approved these changes
늦게까지 고생 많으셨습니다..✊🏻

2023-12-29 02:06 UTC, w00ngja commented on src/Components/Common/Modal/index.tsx
> +        onClick={handleModalClose}
모달 바깥 클릭과 별개로, 우상단이나 좌상단에 X 버튼을 명시해주면 모바일 또는 사용자 경험 측면에서 더 좋지 않을까하는 소소한 의견 내봅니다..😊

2023-12-29 02:08 UTC, miloul approved these changes

2023-12-29 02:08 UTC, miloul commented on src/Components/Common/Modal/index.tsx
> +        $flexDirection={flexDirection}
flexDirection 주신거 너무 좋네요 👍👍

2023-12-29 02:42 UTC, merged

2023-12-29 02:46 UTC, wldlsgur requested changes

2023-12-29 02:46 UTC, wldlsgur commented on src/Components/Common/Modal/style.ts
> +`;
ASK;

궁금한 점 있습니다! z-index를 최상위에 선언하는 방법은 어떻게 생각하시는지 궁금합니다!

Wrapper도 결국 z-index를 가지고 있어야하지 않을까 고민되긴 하네요

2023-12-29 02:46 UTC, wldlsgur commented on src/Components/Common/Modal/type.ts
> +}
ASK;

div 태그로만 구성되었는데 Button속성 타입을 상속받는 이유가 궁금합니다!

2023-12-29 02:46 UTC, wldlsgur commented on src/Components/Common/Modal/style.ts
> +  display: ${(props) => (props.$isOpen ? 'flex' : 'none')};
개인적인 생각인데 isOpen으로 모달 컴포넌트 내부에서 보여줄지 말지 정하고 있고 외부에서 상태 값으로 isOpen을 제어할 것 같습니다!

```JSX
{isModal && <Modal />}}
<Modal isOpen={isModal} />
```

이렇게 분리될 수 있을 것 같은데 첫 번째 방법으로 작성한다면 isOpen의 props가 필요없어도 되지 않을까 하합니다.  

어느 방법이 더 좋은지 잘 모르겠네요ㅜㅜ  익준님 생각은 어떠신가요?

2023-12-29 02:48 UTC, wldlsgur commented on src/Components/Common/Modal/index.tsx
> +  };
```JSX
const handleModalClose = (e: MouseEvent) => { 
   if (target === currentTarget) {
      onChangeOpen(false);
   }
};
```

이렇게 하시면 ref 삭제하셔도 될 것 같습니다!

2023-12-29 02:56 UTC, harry7435 commented on src/Components/Common/Modal/style.ts
> +`;
저도 처음에 z-index를 뒀었는데 안 두어도 클릭이벤트나 영향이 없어서 지웠었는데 두는게 안전할까요?

2023-12-29 02:57 UTC, harry7435 commented on src/Components/Common/Modal/type.ts
> +}
홀리... 나 왜 저렇게 했누 ㅋㅋㅋㅋ 수정할께요

2023-12-29 03:00 UTC, wldlsgur commented on src/Components/Common/Modal/style.ts
> +`;
네네! z-index로 뷰 최상위로 쭉 끌어주시고 음 여유되시면 body태그 하위로 텔포도 생각해볼 수 있을 것 같아요!

텔레포트 안하시면 handleModalClose 핸들러에서 버블링 꼭 막아주시면 됩니다!~

2023-12-29 03:00 UTC, harry7435 commented on src/Components/Common/Modal/style.ts
> +  display: ${(props) => (props.$isOpen ? 'flex' : 'none')};
인혁님 방식대로하게 되면 Modal 컴포넌트를 사용할 때마다 
```ts
{isModal && <Modal />}}
```
위 코드를 매번 작성해주어야 할 꺼 같아서 isOpen props를 받아서 css에서 처리해보려고 합니다!
재웅님이 스타일컴포넌트 css 객체에서 말씀하신 성능적 측면과 같은 맥락으로 모달 표시를 제어하는 로직을
JS로 구현하기보다 css로 제어하는 것이 좀 더 성능적으로 좋지 않을까 생각합니다.

2023-12-29 03:18 UTC, harry7435 commented on src/Components/Common/Modal/style.ts
> +`;
z-index : 10
handleModalClose 핸들러에서 이벤트 버블링 추가

2023-12-29 03:18 UTC, harry7435 commented on src/Components/Common/Modal/style.ts
> +  display: ${(props) => (props.$isOpen ? 'flex' : 'none')};
isOpen props 삭제